### ISSUE TITLE
development: MissingBackendError: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')

### ISSUE THREAD

**Issue by louking** [louking/runningroutes#157]
```
Error on request:
Traceback (most recent call last):
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask_security\decorators.py", line 436, in decorated
    return fn(*args, **kwargs)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask_security\views.py", line 162, in login
    if form.validate_on_submit():
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask_wtf\form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\loutilities\user\__init__.py", line 27, in validate
    if not super().validate():
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask_security\forms.py", line 463, in validate
    if not self.user.verify_and_update_password(self.password.data):
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask_security\core.py", line 828, in verify_and_update_password
    return verify_and_update_password(password, self)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\flask_security\utils.py", line 338, in verify_and_update_password
    verified = _pwd_context.verify(get_hmac(password), user.password)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\passlib\context.py", line 2347, in verify
    return record.verify(secret, hash, **kwds)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\passlib\utils\handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\passlib\handlers\bcrypt.py", line 591, in _calc_checksum
    self._stub_requires_backend()
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\passlib\utils\handlers.py", line 2254, in _stub_requires_backend
    cls.set_backend()
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\passlib\utils\handlers.py", line 2156, in set_backend
    return owner.set_backend(name, dryrun=dryrun)
  File "c:\Users\lking\Documents\Lou's Software\projects\runningroutes\runningroutes\venv-310\lib\site-packages\passlib\utils\handlers.py", line 2176, in set_backend
    raise default_error
passlib.exc.MissingBackendError: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')
```

**Comment by louking** [comment]
created new venv and reinstalled requirements.txt

make sure old venv is deleted, else vscode may find it and use it
