### ISSUE TITLE
deployment: verify email operation

### ISSUE THREAD

**Issue by louking** [louking/runningroutes#61]
```
        Message type:       ERROR
        Location:           /var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/loutilities/tables.py:577
        Module:             tables
        Function:           wrapped_f
        Time:               2020-01-10 14:24:46,753

        Message:

        Traceback (most recent call last):
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/loutilities/tables.py", line 560, in wrapped_f
    self.editor_method_posthook(request.form)
  File "/var/www/www.routes.loutilities.com/runningroutes/runningroutes/runningroutes/views/admin/userrole.py", line 58, in editor_method_posthook
    send_reset_password_instructions(user)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/recoverable.py", line 45, in send_reset_password_instructions
    reset_link=reset_link,
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/core.py", line 986, in send_mail
    return send_mail(*args, **kwargs)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask_security/utils.py", line 492, in send_mail
    mail.send(msg)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/usr/lib64/python3.6/smtplib.py", line 1031, in __init__
    source_address)
  File "/usr/lib64/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python3.6/smtplib.py", line 1037, in _get_socket
    self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by louking** [comment]
Had to fiddle with config file to get this to work. Can't post it here, though
