### ISSUE TITLE
frontend old url redirect exception

### ISSUE THREAD

**Issue by louking** [louking/runningroutes#73]
https://routes.loutilities.com/route/0?fileid=1SCXgsqKiozCtkSXz2UYVSjFWIuYHFNf7ePLkL0sgHkw

```
        Message type:       ERROR
        Location:           /var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py:1891
        Module:             app
        Function:           log_exception
        Time:               2020-01-14 09:00:00,348

        Message:

        Exception on /route/0 [GET]

Traceback (most recent call last):
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/www.routes.loutilities.com/runningroutes/runningroutes/runningroutes/views/frontend/frontend.py", line 196, in get
    return self._renderpage(thisid)
  File "/var/www/www.routes.loutilities.com/runningroutes/runningroutes/runningroutes/views/frontend/frontend.py", line 214, in _renderpage
    route = Route.query.filter_by(id=thisid).one()
  File "/var/www/www.routes.loutilities.com/venv/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3332, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Comment by louking** [comment]
https://stackoverflow.com/questions/13868007/url-in-browser-not-updated-after-call-of-redirect-url-forxxx-in-flask-wit
